# Generated by Django 5.1.7 on 2025-04-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=40)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=20)),
                ('phonenumber', models.CharField(max_length=20)),
            ],
        ),
    ]
